[project]
name = "clarity-voting-tuto"
authors = []
description = ""
telemetry = false

[contracts.color-vote]
path = "contracts/color-vote.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
